### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by paulica40** [AvanthikaMeenakshi/uthiramapp#12]
i am geting this error after i start the server 

GET /sockjs-node/672/aqqwl5yv/websocket 404

**Comment by dipan010** [comment]
i am getting this error

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'C:\Users\palas\Crud app\uthiramapp-master\app.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
